{% set name = "absolv" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/SimonBoothroyd/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 51942b36fac43cc10ee1c9fe6e19e0d29cad0476ce3585ba7fc6e6d06e19087b

build:
  number: 0

outputs:
  - name: {{ name|lower }}-base
    script: build_base.sh
    build:
      noarch: python

    requirements:
      host:
        - python >=3.10
        - pip
        - setuptools
        - setuptools_scm >=8
      run:
        - python >=3.10
        - pydantic >=2
        - tqdm
        - openff-toolkit-base >=0.13.0
        - openff-utilities
        - openmm >=8.0
        - mdtraj
        - femto
        - packmol
        - pymbar >=4.0
      run_constrained:
        - openff-toolkit >=0.13.0

    test:
      imports:
        - absolv

  - name: {{ name|lower }}
    build:
      noarch: python

    requirements:
      host:
        - python >=3.10
      run:
        - python >=3.10
        - rdkit
        - ambertools
        - {{ pin_subpackage('absolv-base', exact=True) }}

    test:
      imports:
        - absolv

about:
  home: https://github.com/SimonBoothroyd/absolv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Absolute solvation free energy calculations with OpenFF and OpenMM
  description: |
    A framework that aims to offer a simple API for computing the change in free energy when transferring
    a solute from one solvent to another, or to vacuum in the case of solvation free energy calculations.
  doc_url: https://simonboothroyd.github.io/absolv/latest/
  dev_url: https://github.com/SimonBoothroyd/absolv

extra:
  recipe-maintainers:
    - simonboothroyd
